import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { CONFIG, VERSION, BUILD_MARKER } from '../src/config.js';
import { PRNG, domainSeed } from '../src/utils/prng.js';
import { CURRICULUM, CurriculumManager } from '../src/sim/curriculum.js';
import { World } from '../src/sim/world.js';
import { RecurrentActorCritic } from '../src/ai/model.js';
import { PPOTrainer } from '../src/ai/ppo.js';
import { computeGAE } from '../src/ai/rollout.js';
import { TrainingSession, nextHistoricalMilestoneAfter } from '../src/ai/session.js';
import { evaluateCurriculumSuite, evaluateFullRetentionSuite } from '../src/evaluation/evaluator.js';

test('release identity is v0.1.1 skill-retention milestone',()=>{assert.equal(VERSION,'0.1.1');assert.equal(BUILD_MARKER,'STABRET-011')});
test('PRNG is repeatable',()=>{const a=new PRNG(123),b=new PRNG(123);for(let i=0;i<100;i++)assert.equal(a.nextUint(),b.nextUint())});
test('seed domains are separated',()=>{assert.notEqual(domainSeed('train',0),domainSeed('heldout:v1',0));assert.notEqual(domainSeed(CONFIG.validation.seedBase,0),domainSeed('heldout:v1',0));assert.notEqual(domainSeed(CONFIG.validation.seedBase,0),domainSeed('train',0))});
test('world generation is deterministic',()=>{const a=new World(77,CURRICULUM[2]),b=new World(77,CURRICULUM[2]);assert.deepEqual(a.food,b.food);assert.deepEqual(a.hazards,b.hazards);assert.deepEqual(a.walls,b.walls);assert.deepEqual(Array.from(a.observe()),Array.from(b.observe()))});
test('world info carries curriculum identity',()=>{const w=new World(7,CURRICULUM[2]);assert.equal(w.info().stageId,2);assert.equal(w.info().stageName,'Obstacle Avoidance')});
test('observations are finite and correct shape',()=>{const w=new World(5,CURRICULUM[0]);const o=w.observe();assert.equal(o.length,10);for(const x of o)assert.ok(Number.isFinite(x))});
test('all actions produce finite rewards',()=>{for(let a=0;a<7;a++){const w=new World(10+a,CURRICULUM[1]);const r=w.step(a);assert.ok(Number.isFinite(r.reward));assert.equal(r.obs.length,10)}});
test('GAE returns finite aligned arrays',()=>{const t=[{env:0,reward:1,value:.2,done:false},{env:0,reward:.5,value:.3,done:true}];const g=computeGAE(t,new Map([[0,0]]));assert.equal(g.advantages.length,2);assert.ok([...g.advantages,...g.returns].every(Number.isFinite))});
test('model checkpoint roundtrip is exact',()=>{const m=new RecurrentActorCritic(9),n=new RecurrentActorCritic(10);n.restore(m.serialize());for(const k of Object.keys(m.params))assert.deepEqual(Array.from(m.params[k]),Array.from(n.params[k]))});
test('training changes parameters without non-finite values',()=>{const s=new TrainingSession({seed:99,envCount:2,autoCurriculum:false});const before=Array.from(s.model.params.wp);s.trainRollout(8);const after=Array.from(s.model.params.wp);assert.notDeepEqual(after,before);for(const arr of Object.values(s.model.params))for(const x of arr)assert.ok(Number.isFinite(x))});

test('curriculum promotion uses sustained rolling performance when retention gate permits',()=>{const c=new CurriculumManager(0);let event=null;for(let i=1;i<=CONFIG.curriculum.minSamples;i++)event=c.noteEpisode({food:3,survived:true},i,{promotionAllowed:true})||event;assert.ok(event);assert.equal(event.reason,'promotion');assert.equal(c.stage,1)});
test('curriculum promotion can be blocked without changing stage',()=>{const c=new CurriculumManager(1);let event=null;for(let i=1;i<=CONFIG.curriculum.minSamples;i++)event=c.noteEpisode({food:3,survived:true},i,{promotionAllowed:false,gateReason:'Foraging retention low'})||event;assert.ok(event);assert.equal(event.reason,'promotion-blocked');assert.equal(c.stage,1);assert.match(event.gateReason,/retention/)});
test('curriculum can demote after sustained collapse',()=>{const c=new CurriculumManager(2);c.cooldownRemaining=0;let event=null;for(let i=1;i<=CONFIG.curriculum.minSamples;i++)event=c.noteEpisode({food:0,survived:false},i)||event;assert.ok(event);assert.equal(event.reason,'demotion');assert.equal(c.stage,1)});

test('validation suite is deterministic for unchanged model and fixed protocol',()=>{const m=new RecurrentActorCritic(42);const a=evaluateCurriculumSuite(m,3,{episodesPerStage:3,seedBase:'validation:test'});const b=evaluateCurriculumSuite(m,3,{episodesPerStage:3,seedBase:'validation:test'});assert.equal(a.protocol,b.protocol);assert.equal(a.score,b.score);assert.deepEqual(a.stageResults,b.stageResults)});
test('full retention validation always covers every skill stage',()=>{const m=new RecurrentActorCritic(43);const r=evaluateFullRetentionSuite(m,{episodesPerStage:2,seedBase:'validation:full-test'});assert.equal(r.maxStage,CURRICULUM.length-1);assert.equal(r.stageResults.length,CURRICULUM.length);assert.ok(r.stageResults.every(x=>Number.isFinite(x.skillScore)&&x.skillScore>=0&&x.skillScore<=1));for(const k of ['balanced','overall','forager','survivor','efficiency'])assert.ok(Number.isFinite(r.categoryScores[k]))});
test('automatic archive establishes all specialist categories',()=>{const s=new TrainingSession({seed:12,envCount:2,autoCurriculum:false});const first=s.runValidation();assert.ok(first.improved);for(const k of ['balanced','overall','forager','survivor','efficiency'])assert.ok(s.getArchiveBrain(k)?.model,k);assert.equal(s.bestBrain,s.getArchiveBrain('balanced'))});
test('regression detector auto-recovers from balanced archive without rewinding experience',()=>{const s=new TrainingSession({seed:13,envCount:2,autoCurriculum:false});s.runValidation();const protectedModel=JSON.stringify(s.bestBrain.model);const beforeSteps=123456;s.totalSteps=beforeSteps;s.model.params.bp[0]+=5;s.bestArchive.balanced.validation.categoryScores.balanced += CONFIG.validation.regressionTolerance + 0.5;const r=s.runValidation();assert.equal(r.regression,true);assert.ok(r.autoRollback);assert.equal(r.autoRollback.automatic,true);assert.equal(s.totalSteps,beforeSteps);assert.equal(JSON.stringify(s.model.serialize()),protectedModel)});
test('restore selected specialist does not rewind total experience counter',()=>{const s=new TrainingSession({seed:14,envCount:2,autoCurriculum:false});s.runValidation();const brain=s.getArchiveBrain('forager');const protectedBp=Array.from(brain.model.params.bp);s.totalSteps=12345;s.model.params.bp[0]+=99;s.restoreBest('forager');assert.deepEqual(Array.from(s.model.params.bp),protectedBp);assert.equal(s.totalSteps,12345);assert.equal(s.rollbackHistory.at(-1).category,'forager')});

test('PPO uses scheduled entropy, bounded adaptive LR and finite KL stats',()=>{const s=new TrainingSession({seed:19,envCount:2,autoCurriculum:false});s.totalSteps=4_000_000;const {metric}=s.trainRollout(8);assert.ok(metric.entropyCoef<CONFIG.ppo.entropyStart);assert.ok(metric.entropyCoef>=CONFIG.ppo.entropyEnd);assert.ok(metric.learningRate>=CONFIG.ppo.minLearningRate&&metric.learningRate<=CONFIG.ppo.maxLearningRate);assert.ok(Number.isFinite(metric.maxEpochKL));assert.ok(metric.epochsRun>=1&&metric.epochsRun<=CONFIG.ppo.epochs)});
test('PPO hard-KL guard rejects an obviously destructive update and restores model',()=>{const model=new RecurrentActorCritic(55);const trainer=new PPOTrainer(model,56);const obs=new Float64Array(CONFIG.model.obsSize);obs[9]=1;const h=model.zeroHidden();const before=model.serialize();const transitions=[0,1,2,3].map((action,i)=>({obs,hPrev:h,action:action%CONFIG.model.actionSize,logProb:-20-i,value:0,reward:0,done:false}));const advantages=new Float64Array([1,-1,1,-1]);const returns=new Float64Array([1,-1,1,-1]);const stats=trainer.update(transitions,advantages,returns,{trainingStep:0});assert.equal(stats.updateRejected,true);assert.deepEqual(model.serialize(),before);assert.ok(trainer.learningRate<CONFIG.ppo.learningRate)});

test('schema-3 checkpoint restore preserves archive and skill state',()=>{const a=new TrainingSession({seed:3,envCount:2,autoCurriculum:false});a.trainRollout(4);a.runValidation();const snap=a.snapshot();const b=new TrainingSession({seed:4,envCount:2,autoCurriculum:false});b.restore(snap);assert.equal(b.totalSteps,a.totalSteps);assert.deepEqual(Array.from(b.model.params.bp),Array.from(a.model.params.bp));assert.equal(b.bestBrain.savedAtSteps,a.bestBrain.savedAtSteps);assert.deepEqual(b.skillBestScores,a.skillBestScores)});
test('schema-2 save migration preserves old protected best and schedules immediate rebaseline',()=>{const a=new TrainingSession({seed:23,envCount:2,autoCurriculum:false});a.trainRollout(4);a.runValidation();const snap=a.snapshot();const legacy={schema:2,seed:snap.seed,totalSteps:3_758_688,totalEpisodes:6000,envSeedCursor:snap.envSeedCursor,curriculum:snap.curriculum,model:snap.model,optimizer:snap.optimizer,metrics:snap.metrics,milestones:snap.milestones,bestBrain:snap.bestBrain,bestBrains:{legacy:snap.bestBrain},validationHistory:[],lastValidationStep:3_500_000,nextValidationStep:3_750_000,rollbackHistory:[]};const b=new TrainingSession({seed:99,envCount:2,autoCurriculum:false});b.restore(legacy);assert.equal(b.totalSteps,3_758_688);assert.ok(b.pendingLegacyBest?.model);assert.equal(b.bestBrain.savedAtSteps,snap.bestBrain.savedAtSteps);assert.equal(b.nextValidationStep,b.totalSteps);const v=b.runValidation();assert.equal(v.validation.maxStage,CURRICULUM.length-1);assert.equal(b.pendingLegacyBest,null);assert.ok(b.getArchiveBrain('balanced'))});
test('schema-1 long-run migration snapshots exact loaded brain and does not backfill fake milestones',()=>{const a=new TrainingSession({seed:44,envCount:2,autoCurriculum:false});const snap=a.snapshot();const steps=2_122_848;const legacy={schema:1,seed:snap.seed,totalSteps:steps,totalEpisodes:3000,envSeedCursor:snap.envSeedCursor,curriculum:{stage:2,history:[]},model:snap.model,optimizer:snap.optimizer,metrics:[],milestones:snap.milestones};const b=new TrainingSession({seed:45,envCount:2,autoCurriculum:false});b.restore(legacy);assert.equal(b.nextMilestoneStep,2_250_000);assert.ok(b.milestones.has(steps));assert.equal(b.milestones.has(1_250_000),false);assert.equal(b.nextValidationStep,b.totalSteps)});

test('reward is decomposed into finite named components',()=>{const w=new World(12345,CURRICULUM[1]);const r=w.step(1);const parts=r.info.rewardParts;for(const k of ['survival','energy','wall','food','hazard','approach','death'])assert.ok(Number.isFinite(parts[k]),k)});
test('v0.1.1 UI exposes specialist archive, skill retention and optimizer safety metrics',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8');for(const id of ['brainSource','bestOption','overallOption','foragerOption','survivorOption','efficiencyOption','restoreBestBtn','skillRetention','lrVal','klVal','epochsVal','retentionAlert'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/SKILL RETENTION/)});

test('historical milestone schedule continues beyond one million steps',()=>{assert.equal(nextHistoricalMilestoneAfter(1_000_000),1_250_000);assert.equal(nextHistoricalMilestoneAfter(2_122_848),2_250_000);assert.equal(nextHistoricalMilestoneAfter(4_999_999),5_000_000);assert.equal(nextHistoricalMilestoneAfter(5_000_000),5_500_000);assert.equal(nextHistoricalMilestoneAfter(20_000_000),21_000_000);assert.equal(nextHistoricalMilestoneAfter(100_000_000),105_000_000)});
test('recovery-safe UI keeps explicit manual/autosave loading and lower-step overwrite guard',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8');const main=await readFile(new URL('../src/app/main.js',import.meta.url),'utf8');assert.match(html,/Load Manual/);assert.match(html,/Load Autosave/);assert.doesNotMatch(main,/loadNewestCheckpoint/);assert.match(main,/storedSteps > session\.totalSteps/);assert.match(main,/lower-step brain was NOT allowed to overwrite it/)});
test('explicit checkpoint restore pauses training for verification',async()=>{const main=await readFile(new URL('../src/app/main.js',import.meta.url),'utf8');assert.match(main,/paused = true/);assert.match(main,/Training is PAUSED so you can verify it/)});
