import { ACTIONS } from '../config.js';
const INPUT_NAMES=['food x','food y','food dist','danger L','danger F','danger R','speed','turn rate','energy','bias'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export class NeuralRenderer{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.mode='ACTIVE';this.nodes=[];this.model=null;this.snapshot=null}
  resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}this.ctx.setTransform(d,0,0,d,0,0);return{w:r.width,h:r.height}}
  draw(model,snapshot){this.model=model;this.snapshot=snapshot;this.nodes=[];const{w,h}=this.resize(),c=this.ctx;c.clearRect(0,0,w,h);c.fillStyle='#050a10';c.fillRect(0,0,w,h);if(!snapshot){c.fillStyle='#78909c';c.font='13px system-ui';c.fillText('Run OBSERVE or PROBE to inspect live activity.',16,28);return}const p=model.params,obs=snapshot.obs,hidden=snapshot.h,probs=snapshot.probs;const inPts=layoutColumn(obs.length,w*.12,h),hidPts=layoutColumn(hidden.length,w*.52,h),outPts=layoutColumn(probs.length+1,w*.88,h);const edges=[];for(let i=0;i<hidden.length;i++)for(let j=0;j<obs.length;j++)edges.push({a:inPts[j],b:hidPts[i],w:p.wx[i*obs.length+j],act:Math.abs(obs[j]*p.wx[i*obs.length+j])});for(let a=0;a<probs.length;a++)for(let i=0;i<hidden.length;i++)edges.push({a:hidPts[i],b:outPts[a],w:p.wp[a*hidden.length+i],act:Math.abs(hidden[i]*p.wp[a*hidden.length+i])});edges.sort((x,y)=>(this.mode==='WEIGHTS'?Math.abs(y.w)-Math.abs(x.w):y.act-x.act));const maxEdges=this.mode==='STRONGEST'?120:Math.min(330,edges.length);c.lineCap='round';for(let k=0;k<maxEdges;k++){const e=edges[k],mag=clamp(Math.abs(e.w),0,1.5),act=clamp(e.act,0,1),alpha=this.mode==='WEIGHTS'?.10+.36*mag:.04+.62*act;c.strokeStyle=e.w>=0?`rgba(92,215,238,${alpha})`:`rgba(236,86,145,${alpha})`;c.lineWidth=.35+1.8*(this.mode==='WEIGHTS'?mag:act);c.beginPath();c.moveTo(e.a.x,e.a.y);const mx=(e.a.x+e.b.x)/2;c.bezierCurveTo(mx,e.a.y,mx,e.b.y,e.b.x,e.b.y);c.stroke()}for(let i=0;i<inPts.length;i++){drawNode(c,inPts[i],obs[i]);this.nodes.push({x:inPts[i].x,y:inPts[i].y,kind:'input',index:i,value:obs[i]})}for(let i=0;i<hidPts.length;i++){drawNode(c,hidPts[i],hidden[i]);this.nodes.push({x:hidPts[i].x,y:hidPts[i].y,kind:'hidden',index:i,value:hidden[i]})}for(let i=0;i<probs.length;i++){drawNode(c,outPts[i],probs[i]);this.nodes.push({x:outPts[i].x,y:outPts[i].y,kind:'output',index:i,value:probs[i]})}const vp=outPts.at(-1);drawNode(c,vp,Math.tanh(snapshot.value));this.nodes.push({x:vp.x,y:vp.y,kind:'value',index:0,value:snapshot.value});c.font='11px system-ui';c.fillStyle='rgba(220,240,247,.72)';for(let i=0;i<inPts.length;i++)c.fillText(INPUT_NAMES[i],inPts[i].x+9,inPts[i].y+4);for(let i=0;i<probs.length;i++){c.textAlign='right';c.fillText(`${ACTIONS[i]} ${(probs[i]*100).toFixed(0)}%`,outPts[i].x-9,outPts[i].y+4)}c.fillText(`VALUE ${snapshot.value.toFixed(2)}`,vp.x-9,vp.y+4);c.textAlign='left';c.fillStyle='rgba(175,210,224,.55)';c.fillText('SENSORY',w*.06,14);c.fillText('RECURRENT STATE',w*.44,14);c.fillText('POLICY / VALUE',w*.78,14)}
  inspectAt(clientX,clientY){if(!this.snapshot||!this.model)return null;const r=this.canvas.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;let best=null,bd=18;for(const n of this.nodes){const d=Math.hypot(x-n.x,y-n.y);if(d<bd){bd=d;best=n}}if(!best)return null;const p=this.model.params;if(best.kind==='input')return`INPUT ${best.index} (${INPUT_NAMES[best.index]}): activation ${best.value.toFixed(4)}`;if(best.kind==='output')return`POLICY ${ACTIONS[best.index]}: probability ${(best.value*100).toFixed(2)}%, bias ${p.bp[best.index].toFixed(4)}`;if(best.kind==='value')return`VALUE HEAD: estimate ${best.value.toFixed(4)}, bias ${p.bv[0].toFixed(4)}`;const i=best.index,obsN=this.snapshot.obs.length,hN=this.snapshot.h.length;const incoming=[];for(let j=0;j<obsN;j++)incoming.push([INPUT_NAMES[j],p.wx[i*obsN+j]]);incoming.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));const outgoing=[];for(let a=0;a<ACTIONS.length;a++)outgoing.push([ACTIONS[a],p.wp[a*hN+i]]);outgoing.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));return`RECURRENT UNIT ${i}: activation ${best.value.toFixed(4)}, bias ${p.bh[i].toFixed(4)} • strongest in ${incoming.slice(0,2).map(x=>`${x[0]} ${x[1].toFixed(3)}`).join(', ')} • strongest out ${outgoing.slice(0,2).map(x=>`${x[0]} ${x[1].toFixed(3)}`).join(', ')}`}
}
function layoutColumn(n,x,h){const top=30,bottom=h-18,span=Math.max(1,bottom-top);return Array.from({length:n},(_,i)=>({x,y:top+(n===1?span/2:(i/(n-1))*span)}))}function drawNode(c,p,v){const a=clamp(Math.abs(v),0,1);c.beginPath();c.arc(p.x,p.y,3.3+3.2*a,0,Math.PI*2);c.fillStyle=v>=0?`rgba(111,226,245,${.25+.75*a})`:`rgba(239,98,152,${.25+.75*a})`;c.fill();c.strokeStyle='rgba(235,250,255,.45)';c.lineWidth=.65;c.stroke()}
