export const VERSION = '0.1.4.0';
export const BUILD_MARKER = 'COGOBS-0140';

export const CONFIG = Object.freeze({
  world: {
    width: 1,
    height: 1,
    maxSteps: 700,
    foodRadius: 0.035,
    hazardRadius: 0.055,
    agentRadius: 0.026,
    wallMargin: 0.018,
    sensorRange: 0.36,
    rayAngles: [-0.72, 0, 0.72],
  },
  physics: {
    accel: 0.0038,
    turnAccel: 0.012,
    drag: 0.965,
    angularDrag: 0.82,
    maxSpeed: 0.016,
    maxAngularSpeed: 0.095,
  },
  energy: {
    initial: 1,
    baseDrain: 0.00125,
    thrustDrain: 0.00115,
    turnDrain: 0.00032,
    foodGain: 0.32,
  },
  rewards: {
    food: 1.0,
    death: -1.0,
    hazard: -0.55,
    wall: -0.035,
    survival: 0.0,
    energyScale: -0.18,
    approachScale: 1.15,
  },
  model: {
    obsSize: 10,
    hiddenSize: 24,
    actionSize: 7,
  },
  curiosity: {
    // Tiny forward-prediction model. The tenth policy observation is a constant
    // bias feature, so curiosity predicts the nine dynamic sensory features.
    hiddenSize: 16,
    predictFeatures: 9,
    learningRate: 0.001,
    adamBeta1: 0.9,
    adamBeta2: 0.999,
    adamEps: 1e-8,
    minibatchSize: 512,
    sampleStride: 4,
    rewardScale: 0.0048,
    maxStepBonus: 0.006,
    maxEpisodeBonus: 0.25,
    errorEmaBeta: 0.995,
    initialErrorMean: 0.18,
    initialErrorVariance: 0.035,
    minErrorScale: 0.01,
    minErrorVariance: 1e-5,
    normalizationWarmupSamples: 512,
    noveltyBaseline: 0.05,
    noveltySigmaSpan: 2.5,
  },
  curiosityAudit: {
    // Controlled A/B ablation: both descendants begin from the exact same policy,
    // optimizer, predictor, curriculum state, environment cursor and action RNG.
    // The CONTROL branch keeps the predictor learning/observing but applies zero
    // intrinsic reward to PPO. The CURIOSITY branch preserves v0.1.3 behavior.
    seedBase: 'heldout:curiosity-ablation:v1',
    episodesPerStage: 8,
    checkpointInterval: 500_000,
    targetStepsPerBranch: 2_000_000,
  },
  stability: {
    // Observational only. These settings control telemetry capture and regression
    // annotation; they never change PPO, curriculum, curiosity, or policy weights.
    captureIntervalSteps: 50_000,
    historyPoints: 240,
    eventHistory: 32,
    validationBalancedDrop: 0.10,
    validationSkillDrop: 0.15,
    spikeWindow: 16,
    spikeMultiplier: 3.0,
  },
  ppo: {
    gamma: 0.985,
    lambda: 0.94,
    clip: 0.12,
    entropyStart: 0.03,
    entropyEnd: 0.008,
    entropyDecaySteps: 5_000_000,
    valueCoef: 0.5,
    learningRate: 0.00015,
    minLearningRate: 0.00005,
    maxLearningRate: 0.0002,
    targetKL: 0.008,
    hardKL: 0.025,
    lrDecrease: 0.55,
    lrIncrease: 1.005,
    lrRecoveryCooldownUpdates: 240,
    entropyRescueLow: 1.25,
    entropyRescueCritical: 0.95,
    entropyRescueLowMultiplier: 1.8,
    entropyRescueCriticalMultiplier: 3.0,
    maxEntropyCoef: 0.08,
    adamBeta1: 0.9,
    adamBeta2: 0.999,
    adamEps: 1e-8,
    maxGradNorm: 0.5,
    epochs: 3,
    minibatchSize: 64,
  },
  curriculum: {
    historySize: 48,
    minSamples: 32,
    transitionCooldownEpisodes: 64,
    blockedPromotionCooldownEpisodes: 24,
    promoteThreshold: 0.72,
    demoteThreshold: 0.18,
    promotionSkillFloor: 0.42,
  },
  validation: {
    seedBase: 'validation:v3',
    episodesPerStage: 12,
    confidenceZ: 1.96,
    regressionTolerance: 0.12,
    improvementEpsilon: 0.004,
    skillWarningDrop: 0.15,
    skillCatastrophicDrop: 0.28,
    forgettingFloor: 0.45,
    confirmationCount: 2,
    balancedConfirmationCount: 2,
    autoRollback: false,
    watchValidationInterval: 50_000,
    championPromotionConfirmations: 2,
    championPromotionMargin: 0.006,
    schedule: [10000, 50000, 100000, 250000, 500000, 750000, 1000000],
    intervalAfterSchedule: 250000,
  },
  continual: {
    // Fraction of newly created training episodes assigned to each curriculum skill.
    // Rows correspond to the current curriculum stage; columns are Motor, Foraging,
    // Obstacle Avoidance, Scarcity. Earlier skills remain in the experience stream.
    rehearsalMix: [
      [1.00, 0.00, 0.00, 0.00],
      [0.25, 0.75, 0.00, 0.00],
      [0.15, 0.20, 0.65, 0.00],
      [0.10, 0.15, 0.20, 0.55],
    ],
    recentMixWindow: 160,
  },
  generalization: {
    seedBase: 'heldout:final:v2',
    compareSeedBase: 'heldout:compare:v2',
    episodesPerStage: 8,
    compareEpisodesPerStage: 4,
    conflictMargin: 0.04,
  },
  runtime: {
    rolloutSteps: 64,
    trainEnvs: 8,
    evalEpisodes: 32,
    compareEpisodes: 24,
    chartPoints: 240,
    learnRenderHz: 12,
    observeRenderHz: 30,
    probeRenderHz: 20,
    learnUiHz: 5,
    curiosityRenderHz: 8,
  },
});

export const ACTIONS = ['COAST', 'THRUST', 'BRAKE', 'LEFT', 'RIGHT', 'THRUST+LEFT', 'THRUST+RIGHT'];
